# Generated by Django 3.0.8 on 2020-08-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frequently_Asked_Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('ans', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_top_Notice', models.CharField(max_length=100)),
                ('shiping_Notice', models.CharField(max_length=100)),
                ('special_cuppon', models.CharField(max_length=50)),
                ('supportHour', models.IntegerField()),
                ('off_day', models.CharField(max_length=500)),
                ('why_off_this_day', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Social_Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helpLine', models.CharField(max_length=200)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('fbLink', models.CharField(max_length=200)),
                ('twiterLink', models.CharField(max_length=200)),
                ('linkedinLink', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Terms_and_Conditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateField(auto_now=True)),
                ('customer_agreement', models.CharField(max_length=8000)),
                ('intellectual_Propertly', models.CharField(max_length=8000)),
                ('Termination', models.CharField(max_length=8000)),
            ],
        ),
        migrations.CreateModel(
            name='Website_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_Title', models.CharField(max_length=200)),
                ('site_Logo', models.ImageField(upload_to='logo')),
                ('physical_address', models.CharField(blank=True, max_length=500)),
                ('site_Description', models.CharField(max_length=500)),
                ('about_Us_short', models.CharField(max_length=500)),
                ('what_we_really_do', models.CharField(max_length=1500)),
                ('history_of_the_company', models.CharField(max_length=1500)),
                ('our_vision', models.CharField(max_length=1500)),
                ('cooperation_detais', models.CharField(max_length=1500)),
                ('support_details', models.CharField(max_length=1500)),
                ('quality_details', models.CharField(max_length=1500)),
                ('delivery_details', models.CharField(max_length=1500)),
                ('customer_care_details', models.CharField(max_length=1500)),
                ('customers_contribution', models.CharField(max_length=1500)),
            ],
        ),
    ]
