# Generated by Django 3.0.8 on 2020-08-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmain', '0002_notice_special_cuppon_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='special_cuppon',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
