# Generated by Django 3.0.8 on 2020-08-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmain', '0003_auto_20200817_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='off_day',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
