# Generated by Django 3.0.8 on 2020-08-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmain', '0004_auto_20200817_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='why_off_this_day',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
