# Generated by Django 3.0.8 on 2020-08-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmain', '0005_auto_20200817_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='website_details',
            name='site_background',
            field=models.ImageField(null=True, upload_to='background'),
        ),
    ]
