# Generated by Django 3.0.8 on 2020-08-05 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilePic', models.ImageField(blank=True, null=True, upload_to='userImg/')),
                ('self_bio', models.CharField(default='You can update your self bio. It might represent you.', max_length=1500)),
                ('self_level', models.IntegerField(default=0)),
                ('total_order', models.IntegerField(default=0)),
                ('total_perchased', models.IntegerField(default=0)),
                ('seller', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
