# Generated by Django 3.0.8 on 2020-08-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_auto_20200827_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_actions',
            name='slider_promotion',
            field=models.BooleanField(default=False),
        ),
    ]
